[package]
name = "zephyr"
version = "0.4.0"
edition = "2021"

[dependencies]
either = "1.14.0"
once_cell = "1.20.2"
tokio = { version = "1.43.0", features = ["full"] }
uuid = { version = "1.15.1", features = ["v4"] }
getrandom = { version = "0.3.0-rc.0" }
